defaults: &defaults
  working_directory: ~/kargo
  docker:
    - image: bradbeam/ansible:2.3.1.0-2
      environment:
        GCE_USER: travis
        OS_USER: ubuntu
        SSH_USER: $GCE_USER
        TEST_ID: "$CI_PIPELINE_ID-$CI_BUILD_ID"
        CONTAINER_ENGINE: docker
        PRIVATE_KEY: $GCE_PRIVATE_KEY
        GS_ACCESS_KEY_ID: $GS_KEY
        GS_SECRET_ACCESS_KEY: $GS_SECRET
        CLOUD_MACHINE_TYPE: "g1-small"
        ANSIBLE_KEEP_REMOTE_FILES: "1"
        ANSIBLE_CONFIG: ./tests/ansible.cfg
        BOOTSTRAP_OS: none
        DOWNLOAD_LOCALHOST: "false"
        DOWNLOAD_RUN_ONCE: "false"
        IDEMPOT_CHECK: "false"
        RESET_CHECK: "false"
        UPGRADE_TEST: "false"
        RESOLVCONF_MODE: docker_dns
        LOG_LEVEL: "-vv"
        ETCD_DEPLOYMENT: "docker"
        KUBELET_DEPLOYMENT: "docker"
        VAULT_DEPLOYMENT: "docker"
        WEAVE_CPU_LIMIT: "100m"
        MAGIC: "ci check this"
openstack_vars: &openstack_vars
  environment:
    TF_VAR_username: ${OS_USERNAME}
    TF_VAR_password: ${OS_PASSWORD}
    TF_VAR_tenant: ${OS_TENANT_NAME}
    TF_VAR_auth_url: ${OS_AUTH_URL}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      #- echo $PRIVATE_KEY | base64 -d > $HOME/.ssh/id_rsa
      #- echo $GCE_PEM_FILE | base64 -d > $HOME/.ssh/gce
      #- echo $GCE_CREDENTIALS > $HOME/.ssh/gce.json
      #- chmod 400 $HOME/.ssh/id_rsa

      # - run:
      #     name: Create terraform remote state file
      #     command: >
      #       echo -e "terraform {\n  backend \"gcs\" {\n    bucket  = \"kubespray-ci-state\"\n    path    = \"ci/${CIRCLE_SHA1}.tfstate\"\n    project = \"kargo-ci\"\n  }\n}" > remote.tfvars
      # - run:
      #     name: Render gce service account
      #     command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      # - run:
      #     name: pwd + ls
      #     command: pwd && ls -la
      # - persist_to_workspace:
      #     root: /root
      #     paths:
      #       - .
  ansible_dry_run:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dummy inventory file
          command: echo -e "[local]\n127.0.0.1" > ansible_syntax_hosts
      - run:
          name: Ansible syntax check
          command: ansible-playbook --syntax-check --list-tasks -i ansible_syntax_hosts cluster.yml
  create-openstack:
    <<: *defaults
    <<: *openstack_vars
    steps:
      - checkout
      - run:
          name: Generate temporary ssh keypair
          command: |
            if [ ! -f ~/.ssh/id_rsa_ci ]; then
              ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa_ci
            fi
      - run:
          name: Install terraform
          command: |
            if [ ! -f ./terraform ]; then
              curl -O https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip
              unzip terraform_0.9.11_linux_amd64.zip
            fi
      - run:
          name: Provision environment on openstack
          command: >
            ./terraform apply
            -state=contrib/terraform/openstack/terraform.tfstate
            -var 'number_of_k8s_masters="0"'
            -var 'number_of_k8s_masters_no_floating_ip="3"'
            -var 'number_of_k8s_nodes_no_floating_ip="2"'
            -var 'number_of_k8s_nodes="0"'
            -var 'image="ubuntu-xenial"'
            -var 'flavor_k8s_master="ea762e25-7320-484d-b95d-747a1373c791"'
            -var 'flavor_k8s_node="ea762e25-7320-484d-b95d-747a1373c791"'
            -var 'flavor_bastion="ea762e25-7320-484d-b95d-747a1373c791"'
            -var 'floatingip_pool="Public"'
            -var 'external_net="113d4b08-0fc4-478c-9eae-4ecfb086e3f4"'
            -var 'cluster_name="ci-'${CIRCLE_SHA1}'"'
            -var 'network_name="ci-'${CIRCLE_SHA1}'"'
            -var 'public_key_path=~/.ssh/id_rsa_ci.pub'
            contrib/terraform/openstack
      - persist_to_workspace:
          root: /root
          paths:
            - .
      - run:
          name: Wait for apt-get update to run
          command: sleep 30
  wait-for-jobs:
    <<: *defaults
    <<: *openstack_vars
    steps:
      - run:
          name: Watch circleci for no running/pending/queued tasks
          command: |
            count=0
            while true; do
              active_jobs=$(curl -s -H 'Accept: application/json' \
              "https://circleci.com/api/v1/project/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}?circle-token=${CIRCLE_PROJECT_API_TOKEN}&limit=100" | \
              jq '.[] | select((.workflows.workflow_id = "'${CIRCLE_WORKFLOW_ID}'") and (.status | test("running|pending|queued"))) | .build_num')
              # Test if we're the only active job
              if [[ "${active_jobs}" == "${CIRCLE_BUILD_NUM}" || -z "${active_jobs}" ]]; then
                ((count+=1))
              fi
              # We'll wait for two iterations before breaking out of this watch loop
              # to make sure we're not catching the inbetween phase of waiting for
              # a job to get started/scheduled
              if (( ${count} == 2 )); then
                break
              fi
              sleep 10
            done
  destroy-openstack:
    <<: *defaults
    <<: *openstack_vars
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: pwd + ls
          command: pwd && ls -la
      - run:
          name: find tfstate
          command: find /root -name "*.tfstate" -exec ls -l {} \;
      - run:
          name: Destroy environment on openstack
          command: >
            ./terraform destroy
            --force
            -state=contrib/terraform/openstack/terraform.tfstate
  # create-gce:
  #     working_directory: ~/kargo
  #     steps:
  #       - >
  #         ansible-playbook tests/cloud_playbooks/create-gce.yml -i tests/local_inventory/hosts.cfg -c local
  #         ${LOG_LEVEL}
  #         -e cloud_image=${CLOUD_IMAGE}
  #         -e cloud_region=${CLOUD_REGION}
  #         -e gce_credentials_file=${HOME}/.ssh/gce.json
  #         -e gce_project_id=${GCE_PROJECT_ID}
  #         -e gce_service_account_email=${GCE_ACCOUNT}
  #         -e cloud_machine_type=${CLOUD_MACHINE_TYPE}
  #         -e inventory_path=${PWD}/inventory/inventory.ini
  #         -e kube_network_plugin=${KUBE_NETWORK_PLUGIN}
  #         -e mode=${CLUSTER_MODE}
  #         -e test_id=${TEST_ID}
  #         -e startup_script="'${STARTUP_SCRIPT}'"

  # ansible:
  #   steps:
  #     - run:
  #         name: Run ansible playbook cluster.yml
  #         command: >
  #           ansible-playbook -i inventory/inventory.ini -b --become-user=root --private-key=${HOME}/.ssh/id_rsa -u $SSH_USER
  #           ${SSH_ARGS}
  #           ${LOG_LEVEL}
  #           -e ansible_python_interpreter=${PYPATH}
  #           -e ansible_ssh_user=${SSH_USER}
  #           -e bootstrap_os=${BOOTSTRAP_OS}
  #           -e cert_management=${CERT_MGMT:-script}
  #           -e cloud_provider=gce
  #           -e deploy_netchecker=true
  #           -e download_localhost=${DOWNLOAD_LOCALHOST}
  #           -e download_run_once=${DOWNLOAD_RUN_ONCE}
  #           -e etcd_deployment_type=${ETCD_DEPLOYMENT}
  #           -e kube_network_plugin=${KUBE_NETWORK_PLUGIN}
  #           -e kubelet_deployment_type=${KUBELET_DEPLOYMENT}
  #           -e local_release_dir=${PWD}/downloads
  #           -e resolvconf_mode=${RESOLVCONF_MODE}
  #           -e vault_deployment_type=${VAULT_DEPLOYMENT}
  #           --limit "all:!fake_hosts"
  #           cluster.yml
  # destroy-openstack:
  #   steps:
  #     - run:
  #         name: Provision environment on openstack
  #         command: >
  #           ./terraform destroy
  #           --force
  #           -state=contrib/terraform/openstack/terraform.tfstate
  #           -var-file=contrib/terraform/openstack/kargo.tfvars
  # ubuntu_calico_rkt_sep:
  #   steps:
  #     - run: echo
  #   environment:
  #     KUBE_NETWORK_PLUGIN: calico
  #     CLOUD_IMAGE: ubuntu-1604-xenial
  #     CLOUD_REGION: us-central1-b
  #     CLUSTER_MODE: separate
  #     ETCD_DEPLOYMENT: rkt
  #     KUBELET_DEPLOYMENT: rkt
  #     STARTUP_SCRIPT: ""

workflows:
  version: 2
  build_openstack_and_test:
    jobs:
      - build
      - ansible_dry_run:
          requires:
            - build
      - create-openstack:
          requires:
            - ansible_dry_run
      - wait-for-jobs:
          requires:
            - build
      - destroy-openstack:
          requires:
            - wait-for-jobs
